apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argo-rollouts
  namespace: flux-system
spec:
  interval: 1m
  targetNamespace: argo-rollouts
  install:
    createNamespace: true
  chart:
    spec:
      chart: argo-rollouts
      sourceRef:
        kind: HelmRepository
        name: argo-rollouts-source
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 1