apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-nats
  namespace: flux-system
spec:
  interval: 1m
  targetNamespace: nats
  install:
    createNamespace: true
  chart:
    spec:
      chart: nats
      sourceRef:
        kind: HelmRepository
        name: nats-source
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 1