apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: project-gitops-app
  namespace: flux-system
spec:
  targetNamespace: dwk-project
  install:
    createNamespace: true
  sourceRef:
    kind: GitRepository
    name: dwk-repo
  interval: 1m
  path: ./project/manifests
  prune: true
  validation: client